services:
  localstack:
    image: localstack/localstack:3.0
    environment:
      SERVICES: dynamodb, s3
      DYNAMODB_SHARE_DB: 1
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_DDB_INIT_DIR:-./docker/localstack/dynamodb_init.sh}:/etc/localstack/init/ready.d/dynamodb_init.sh"
      - "${LOCALSTACK_S3_INIT_DIR:-./docker/localstack/s3_init.sh}:/etc/localstack/init/ready.d/s3_init.sh"
      - "${LOCALSTACK_S3_DATA_DIR:-./docker/localstack/s3/data/sample}:/home/localstack/data/sample"
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: localstack:4566
    ports:
      - 8001:8001
    depends_on:
      - localstack
    profiles:
      - debug # docker-compose --profile debug up
