services:
  localstack:
    image: localstack/localstack:3.0
    environment:
      SERVICES: dynamodb, s3
      DYNAMODB_SHARE_DB: 1
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_DDB_INIT_DIR:-./localstack/dynamodb/init.sh}:/etc/localstack/init/ready.d/dynamodb_init.sh"
      - "${LOCALSTACK_DDB_DATA_DIR:-./localstack/dynamodb/data}:/home/localstack/data/dynamodb"
      - "${LOCALSTACK_S3_INIT_DIR:-./localstack/s3/init.sh}:/etc/localstack/init/ready.d/s3_init.sh"
      - "${LOCALSTACK_S3_DATA_DIR:-./localstack/s3/data}:/home/localstack/data/s3"
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: localstack:4566
    ports:
      - 8001:8001
    depends_on:
      - localstack
    # profiles:
    #   - debug # docker-compose --profile debug up
